version: '3.3'
services:
    assembly:
        build: .
        volumes:
            - webapps:/usr/local/tomcat/webapps/
    prod:
        image: tomcat
        volumes:
            - webapps:/usr/local/tomcat/webapps/
        ports:
            - 8080:8080
        depends_on:
             - assembly
volumes:
    webapps: