---
- name: build
  hosts: build
  become: yes

  tasks:
    - name: Ensure maven package is present
      apt:
          name: maven
          state: present

    - name: Clone a repo
      git:
          repo: https://github.com/jleetutorial/maven-project
          dest: /tmp/maven-project

    - name: maven build
      shell: mvn clean package
      args:
          chdir: /tmp/maven-project/webapp


- name: production
  hosts: production
  become: yes

  tasks:
    - name: Ensure tomcat package is present
      apt:
          name: tomcat8
          state: present

    - name: copy build files
      synchronize: src=/tmp/maven-project/webapp/target/webapp.war dest=/var/lib/tomcat8/webapps
      delegate_to: build
