---
- name: install nginx
  hosts: web
  become: yes

  tasks:
      - name: Ensure nginx package is present
        apt:
            name: nginx
            state: present

      - name: Replace string
        lineinfile:
          path: /var/www/html/index.nginx-debian.html
          regexp: '<h1>Welcome to nginx!</h1>'
          line: '<h1><p><script> document.write(new Date().toLocaleDateString()); </script></p></h1>'